### ISSUE TITLE
ASD images not loading

### ISSUE THREAD

**Issue by VitahuHere** [bibixx/zdaj-se-pjatk#34]
![image](https://user-images.githubusercontent.com/79806896/213896621-19ece9c9-20ec-41da-aeb6-c6e5770e0e40.png)
Tried with different browsers, devices, not working

**Comment by bibixx** [comment]
I am not unfortunately scraping and hosting the images present on mykhi so those are hosted directly from there. To work around this issue go to https://pja.mykhi.org/generatory2.0/, complete the CAPTCHA challenge and then reload zdaj.se (may take a few tries)

**Comment by Lukaszz112** [comment]
i didn't have any CAPTCHA in [](https://pja.mykhi.org/generatory2.0/)
