### ISSUE TITLE
Powtarzające się pytanie z różnymi odpowiedziami

### ISSUE THREAD

**Issue by s27049pjwstk** [bibixx/zdaj-se-pjatk#35]
To samo pytanie ma dwie różne poprawne odpowiedzi oraz się powtarza w jednym teście.
![image](https://user-images.githubusercontent.com/124628842/217077143-7ad4678e-cc09-49ac-8320-cc76dfde48a5.png)
![image](https://user-images.githubusercontent.com/124628842/217077174-f1e644af-fbf8-47ee-99ea-6e9dd9276c6a.png)

**Comment by bibixx** [comment]
@s27049pjwstk moved to https://github.com/bibixx/zdaj-se-pjatk-data/issues/22
