### ISSUE TITLE
Powtarzające się pytanie

### ISSUE THREAD

**Issue by s27049pjwstk** [bibixx/zdaj-se-pjatk#36]
Praktycznie identyczne pytanie powtórzone w jednym tym samym wygenerowanym teście.
![image](https://user-images.githubusercontent.com/124628842/217077411-fadf0a3d-ad15-4358-9057-dfecf1f01ad1.png)
![image](https://user-images.githubusercontent.com/124628842/217077432-99b6565d-501d-4480-b9bc-617ef1faa559.png)

**Comment by bibixx** [comment]
@s27049pjwstk moved to https://github.com/bibixx/zdaj-se-pjatk-data/issues/22
