### ISSUE TITLE
Powtarzające się odpowiedzi w pytaniu

### ISSUE THREAD

**Issue by s27049pjwstk** [bibixx/zdaj-se-pjatk#37]
Odpowiedzi 2 i 4 są takie same.
![image](https://user-images.githubusercontent.com/124628842/217078392-e4842688-c964-45a7-8131-0fc006743d7e.png)

**Comment by bibixx** [comment]
@s27049pjwstk moved to https://github.com/bibixx/zdaj-se-pjatk-data/issues/22
