### ISSUE TITLE
Problem z załadowaniem zdjec na ASD

### ISSUE THREAD

**Issue by Lukaszz112** [bibixx/zdaj-se-pjatk#45]
<img width="875" alt="Zrzut ekranu 2024-05-12 o 12 34 05" src="https://github.com/bibixx/zdaj-se-pjatk/assets/93291505/82f07d4a-2133-4a0c-a2a7-42a4bd53f3cd">

**Comment by bibixx** [comment]
https://github.com/bibixx/zdaj-se-pjatk/issues/34

**Comment by bibixx** [comment]
Hmm, actually it seems to be a different issue this time. I will try to investigate this next week

**Comment by bibixx** [comment]
I've added scraping and hosting of the images now. It should be working correctly from now on and the solution from #34 is not needed anymore
